-- ── Enums ─────────────────────────────────────────────────────────────────────

CREATE TYPE public.media_type AS ENUM ('photo', 'video');
CREATE TYPE public.artifact_status AS ENUM ('uploading', 'ready', 'failed');

-- ── artifacts ─────────────────────────────────────────────────────────────────
-- One row per uploaded photo or video. The id is generated by the client before
-- upload so it can double as the R2 folder name: artifacts/{id}/original.jpg

CREATE TABLE public.artifacts (
  id                    uuid                  PRIMARY KEY,
  uploaded_by           uuid                  NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  media_type            public.media_type     NOT NULL,
  status                public.artifact_status NOT NULL DEFAULT 'uploading',
  width                 integer               NOT NULL,
  height                integer               NOT NULL,
  duration_seconds      numeric,
  original_content_type text                  NOT NULL,
  file_size_bytes       bigint                NOT NULL,
  taken_at              timestamptz,
  created_at            timestamptz           NOT NULL DEFAULT now(),
  updated_at            timestamptz           NOT NULL DEFAULT now(),
  deleted_at            timestamptz
);

CREATE INDEX artifacts_uploaded_by_idx ON public.artifacts (uploaded_by);

-- Reuse the set_updated_at function created in the albums migration
CREATE TRIGGER artifacts_set_updated_at
  BEFORE UPDATE ON public.artifacts
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.artifacts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "uploader can select artifacts"
  ON public.artifacts FOR SELECT
  USING (uploaded_by = auth.uid() AND deleted_at IS NULL);

CREATE POLICY "uploader can insert artifacts"
  ON public.artifacts FOR INSERT
  WITH CHECK (uploaded_by = auth.uid());

CREATE POLICY "uploader can update artifacts"
  ON public.artifacts FOR UPDATE
  USING (uploaded_by = auth.uid());

CREATE POLICY "uploader can delete artifacts"
  ON public.artifacts FOR DELETE
  USING (uploaded_by = auth.uid());

-- ── album_artifacts ───────────────────────────────────────────────────────────
-- Join table connecting artifacts to albums. Soft-removes via removed_at so we
-- keep a history of what was in an album without hard-deleting rows.

CREATE TABLE public.album_artifacts (
  album_id      uuid        NOT NULL REFERENCES public.albums(id) ON DELETE CASCADE,
  artifact_id   uuid        NOT NULL REFERENCES public.artifacts(id) ON DELETE CASCADE,
  position      numeric     NOT NULL,
  added_by      uuid        NOT NULL REFERENCES auth.users(id),
  added_at      timestamptz NOT NULL DEFAULT now(),
  removed_at    timestamptz,
  removed_by    uuid        REFERENCES auth.users(id),
  PRIMARY KEY (album_id, artifact_id)
);

CREATE INDEX album_artifacts_album_id_idx ON public.album_artifacts (album_id);

ALTER TABLE public.album_artifacts ENABLE ROW LEVEL SECURITY;

-- Album owner can see all active (not removed) entries for their albums
CREATE POLICY "album owner can select album_artifacts"
  ON public.album_artifacts FOR SELECT
  USING (
    removed_at IS NULL
    AND EXISTS (
      SELECT 1 FROM public.albums
      WHERE id = album_id AND owner_id = auth.uid()
    )
  );

CREATE POLICY "album owner can insert album_artifacts"
  ON public.album_artifacts FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.albums
      WHERE id = album_id AND owner_id = auth.uid()
    )
  );

CREATE POLICY "album owner can update album_artifacts"
  ON public.album_artifacts FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.albums
      WHERE id = album_id AND owner_id = auth.uid()
    )
  );

CREATE POLICY "album owner can delete album_artifacts"
  ON public.album_artifacts FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM public.albums
      WHERE id = album_id AND owner_id = auth.uid()
    )
  );
